# Site settings
title: EIP Nyxo
email: eipnyxo@gmail.com
url: //eipnyxo.github.io
description: "Le site du projet Nyxo"
skills: ""

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  odd: 1ac9a7
  even: 18bd9d

# Footer settings
footer:
  copyright: Nyxo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/eipnyxo


# Build settings
markdown: kramdown
permalink: pretty
