# Site settings
title: EIP Nyxo
email: eipnyxo@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://eipnxo.github.io" # the base hostname & protocol for your site
github_username:  eipnyxo

# Build settings
markdown: kramdown
